### ISSUE TITLE
client close immediate just after connection create

### ISSUE THREAD

**Issue by superbogy** [localtunnel/server#100]
debug info like this:

```
  localtunnel:server making new client with id witty-liger-51 +0ms
  lt:TunnelAgent[witty-liger-51] tcp server listening on port: 33323 +0ms
  lt:ClientManager removing client: witty-liger-51 +0ms

```

**Comment by superbogy** [comment]
i run in the top level of domain and add *  A name for subdomains

**Comment by superbogy** [comment]
I had found the reason, It is that network of my vps was transform and proxy for many times in the 
 tencent cloud vpc.  Close this issue~!

**Comment by khoazero123** [comment]
@superbogy I have same the problem :( How did you solve this problem? (I run it on VPS of OVH)

**Comment by indrasantosa** [comment]
I also have the same problem, is there anyone can advise me how to solve this problem?

**Comment by batusekerci** [comment]
I encountered this problem too, is there any fix?
