### ISSUE TITLE
Subdomain character limit too low

### ISSUE THREAD

**Issue by BrandonZacharie** [localtunnel/server#30]
The current character limit prohibits me from using anything more than my computer's name (e.g. `brandon-macbook-pro`) as a subdomain. I'd like it to be my computer's full hostname plus my project and company name (i.e. `brandon-macbook-pro.local.api.acme`). The [domain names specification](http://tools.ietf.org/html/rfc1035#section-3.1) permits subdomains **63** characters in length or less. It would be awesome if we could get the limit changed from 20 to 63.

**Comment by defunctzombie** [comment]
PR welcome for review :)

**Comment by a7medkamel** [comment]
This issue is already merged... Issue should be closed
