### ISSUE TITLE
Only support top level  domain

### ISSUE THREAD

**Issue by bastengao** [localtunnel/server#31]
It not works when host domain is not top level domain. I want to use subdomain as base domain described in https://github.com/localtunnel/server#use-your-server, such as `subdomain.example.com` and `*.subdomain.example.com`. This issue is similar to #21.

**Comment by lukehorvat** [comment]
Are you getting a `no active client` error? I am.

I've been doing a little debugging, and logging `hostname` and `subdomain` just above [this line](https://github.com/localtunnel/server/blob/master/server.js#L49) yields `xxxxxxxxx.localtunnel.example.com` and `xxxxxxxxx.localtunnel` respectively. As a result, I get the error `no active client for 'xxxxxxxxx.localtunnel'` when I visit http://xxxxxxxxx.localtunnel.example.com in my browser.

@defunctzombie I think `var client_id = subdomain;` needs to be changed to handle this use case. Perhaps check if `subdomain` has a dot and, if so, extract the substring up to the first dot?

**Comment by lukehorvat** [comment]
Furthermore, http://localtunnel.example.com/?new (requested when the client starts up) results in `subdomain`'s value being `localtunnel`. So it won't get to [this line](https://github.com/localtunnel/server/blob/master/server.js#L46) and the `new_client` function won't be called.

**Comment by boris** [comment]
Having the same problem here. When using http://sub.domain.com it returns a 502.

```
lt --host http://sub.domain.com:1443 -p 9001
502

Error: localtunnel server returned an error, please try again
    at Request._callback (/usr/lib/node_modules/localtunnel/lib/Tunnel.js:54:13)
    at Request.self.callback (/usr/lib/node_modules/localtunnel/node_modules/request/main.js:122:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/localtunnel/node_modules/request/main.js:655:16)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/localtunnel/node_modules/request/main.js:617:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

But if I use http://domain.com:

```
lt --host http://domain.com:1443 -p 9001
your url is: http://jddrzcnonz.domain.com:1443
```

**Comment by worg** [comment]
I think a startup flag should be provided that marks the current server as 'subdomain' server, thus allowing us to change the check performed [here](https://github.com/localtunnel/server/blob/master/server.js#L45) , I'll be glad to submit a PR

**Comment by boris** [comment]
@worg sounds good. In fact, I found a workaround with the following modification on the `server.js`;
 (here's the diff)

```
diff --git a/server.js b/server.js
index 17c2d9f..52db061 100644
--- a/server.js
+++ b/server.js
@@ -41,8 +41,11 @@ function maybe_bounce(req, res, bounce) {
         return false;
     }

-    var subdomain = tldjs.getSubdomain(hostname);
-    if (!subdomain) {
+    var subdomain = hostname.split(".")[0];
+    console.log(subdomain)
+
+    //var subdomain = tldjs.getSubdomain(hostname);
+    if (subdomain === 'tunnel') {
         return false;
     }
```

But, I believe a startup flag is a better solution.

**Comment by gabrieleds** [comment]
+1

**Comment by fuzziness** [comment]
+1

**Comment by defunctzombie** [comment]
There are a few PRs out to solve this issue; once those merge this will be resolved.
