### ISSUE TITLE
subdomain lookup fails when running on localhost

### ISSUE THREAD

**Issue by a7medkamel** [localtunnel/server#38]
the server uses tldjs to extract subdomains. but tldjs doesn't consider localhost a valid domain; so subdomain lookup fails and proxy calls fallback to the /www page

Looks like we need to add the following line atop server.js

``` javascript
tldjs.validHosts = ['localhost'];
```

let me know if you have any concerns before I send a pull request.

**Comment by defunctzombie** [comment]
The server code has been heavily refactored and a new _--domain_ option added for running on non-standard domains or subdomains.
