### ISSUE TITLE
"--local-host" option not working with "--host"

### ISSUE THREAD

**Issue by fabiovianadotcom** [localtunnel/server#42]
I'm running the current "master" localtunnel server, but when i run in my machine this command:

``` bash
lt --port 80 --subdomain example --local-host example.dev --host hello.com
```

The option "--local-host" is somehow overwritten by "localhost".

When I use this command:

``` bash
lt --port 80 --subdomain example --local-host example.dev
```

The option "--local-host" work very well, that's why I'm assuming the problem is on the localtunnel server.

**Comment by defunctzombie** [comment]
The server code has been heavily refactored.
