### ISSUE TITLE
Request problem

### ISSUE THREAD

**Issue by mikrafizik** [localtunnel/server#45]
We are using localtunnel to expose some local REST Api to the world. We installed localtunnel to our web server but looks like something is wrong. Tunnel works in 1 case out of 100. We get error

> no more client, queue callback 

and can't get response from the local server.
Do I miss something?

Server starts like:

`bin/server --port 1234  //display your index.html`

Localhost client:

`lt  --host http://*myhost*:1234 --port 80 --open`

and i get url 

> your url is: http://smcowmlcpe.*myhost*:123

**Comment by jeremieweldin** [comment]
+1

**Comment by defunctzombie** [comment]
The server has been refactored heavily; please try a newer version of the server and open a new issue with steps to reproduce if the issue persists.
