### ISSUE TITLE
Server not closing connection if client shutdown

### ISSUE THREAD

**Issue by rijotech** [localtunnel/server#46]
I noticed the server doesn't close the connection is client was forcefully shut down and i was wondering how could i implement a close client connection if connection is not active? that way preventing problem, for example if client is using a custom sub domain and tries to reconnect it won't be able to used the same custom sub domain cause the current connection is still open in the server side and the server will assign a random sub domain even if you specified to use an specific sub domain. 

I also noticed that if you tried to reconnect to your previous connection using previous sub domain the server will crash giving you a `[error] bookrc.js:8 read ECONNRESET`
Any ideas on how to fix this issue?

**Comment by defunctzombie** [comment]
Which client does this refer to? The `lt` process?

**Comment by defunctzombie** [comment]
Server has undergone a code refactor.
