### ISSUE TITLE
Server return 404 when trying to connect via websockets

### ISSUE THREAD

**Issue by Skylion007** [localtunnel/server#48]
So I tried to reverse DNS my WEBRTC server since Chrome now requires HTTPS to allow the user to use the site. Unfortunately, when attempting to connect via /webrtc, instead of forwarding my websocket to the server, the site just returns 404, <mysubdomain>.localtunnel.me/webrtc not found. Does this software support websocket connections? If so, what am I doing wrong? Do I just have something misconfigured or the is problem with the actual functionality of this server?

I was using Chromium's Webrtc Server through webrtc_ros for further information.

**Comment by defunctzombie** [comment]
Websockets are supported in localtunnel webrtc is likely not.
