### ISSUE TITLE
Bad Gateway Response

### ISSUE THREAD

**Issue by jgrauel** [localtunnel/server#51]
I have setup Localtunnel, and have successfully received the sub domain, however any attempt to test my api with the url results in a "502 Bad Gateway" response. 
Is there something i didn't set up correct? I can confirm my localhost:5000 is working, and that is the port I provided.
Thanks

**Comment by jgrauel** [comment]
sorry I meant for this to be in the client - I will move there.

**Comment by AndrejfSantos** [comment]
I am having the same issue, any updates on this?

**Comment by kwoxer** [comment]
Still same issue here with the latest version. Any update?

Tested in Firefox/Chrome.
