### ISSUE TITLE
static files not fully loaded

### ISSUE THREAD

**Issue by olup** [localtunnel/server#60]
I posted an issue on the client side, but as i believe the error comes form the server somehow i am posting it here too.
Also i have seen some other issues relating to the same error, but no definitive answer has been provided.
The problem is my react-webpack app bundle a mid-sized vendor.js file (270kb) that has to be loaded by my single page application. But strangely, the file almost never seems to load completely. When i use my browser to access it i can see that it gets truncated in the middle. The browser seems to be loading but nothing more pass through, at least not all the time (sometimes it manage to load, maybe ith help of the cache)
Note that it seems to fail always at the same points
Any idea to fix the behavior ?

**Comment by defunctzombie** [comment]
I have no idea. Without a reproducible test case there could be many issues here (like the localtunnel server dying part way through the requests).
