### ISSUE TITLE
tunnel server is offline

### ISSUE THREAD

**Issue by khalil-rashow** [localtunnel/server#62]
Hi guys,

when running a client via lt --host http://sub.example.tld:1234 --port 9000
after running server by node server --port 1234
I got this error: 
tunnel server offline: getaddrinfo ENOTFOUND sub.example.tld sub.example.tld:1234, retry 1s
I dont get any msj showing that the server is running on port 1234.

thanks in advance.

**Comment by netProphET** [comment]
Similar problem here, error is
```
tunnel server offline: Invalid protocol: 1.2.3.4:, retry 1s
```
(Actual IP address redacted.)

**Comment by seliver** [comment]
As far as I know, localtunnel server doesn't work when initiated on subdomains.
Check my fork, I'm trying a workaround for this.
