### ISSUE TITLE
Server binds to 0.0.0.0

### ISSUE THREAD

**Issue by chmduquesne** [localtunnel/server#67]
Hi!

I noticed that the server binds to all adresses. It would be nice, when proxying the requests, to make it listen on localhost only (or even better, having it listen to a unix socket). Instead of having the option:

    --port <number>

Could we have:

    --listen <host:ip|unix-socket>

Cheers!

**Comment by chmduquesne** [comment]
Just to clarify: I am writing this because I don't want to pull docker as a dependency, but I still want to run this process behind nginx and keep the corresponding port closed to the outside world.

**Comment by defunctzombie** [comment]
/shrug If you want to make a PR I can review. I do not view "I don't want to pull docker as a dependency" as reason alone for me to work on this change.

**Comment by defunctzombie** [comment]
Added via https://github.com/localtunnel/server/commit/d7852a3dd1b7987d2c805f87cb38d0078352073e
