### ISSUE TITLE
Server at localtunnel.me fails to detect occupied subdomains

### ISSUE THREAD

**Issue by quietopus** [localtunnel/server#70]
**First Invocation**
```
$ lt -p 89 -s testing123
your url is: https://testing123.localtunnel.me
```
**Second Invocation**
(Started on the same machine, without terminating the first invocation.)
```
$ lt -p 90 -s testing123
your url is: https://testing123.localtunnel.me
```

The following also happens:

**First Invocation**
```
$ lt -p 89
your url is: https://inpvvzkfuo.localtunnel.me
```
**Second Invocation**
```
$ lt -p 90 -s inpvvzkfuo
your url is: https://inpvvzkfuo.localtunnel.me
```

As far as I can tell, visiting the conflicting domain delivers responses consistent with the first invocation.

**Comment by siburny** [comment]
It does actually detect, and then it generates a new subdomain (client id): https://github.com/localtunnel/server/blob/48475a404b632739fc1a16efb1d74e48f78ab75f/server.js#L191

**Comment by defunctzombie** [comment]
The response url from the server was incorrect in the case where it detects and replaces with a random url; this has been fixed now.
