### ISSUE TITLE
secret for connections

### ISSUE THREAD

**Issue by Freundschaft** [localtunnel/server#73]
I have an issue where hosting localtunnel unprotected on the internet would cause issues with random people connecting to my server. how can I protect my localtunnel server with a password or certificate?

**Comment by jonathanarbely** [comment]
How do you 'detect' other people visiting your content? Do you host the server component yourself or do you use the default CLI?

**Comment by Freundschaft** [comment]
Im using the server component to host myself

**Comment by defunctzombie** [comment]
This is not a feature of localtunnel server.

**Comment by igauravsehrawat** [comment]
@defunctzombie Will this be a feature now. https://github.com/localtunnel/localtunnel/issues/158

Thanks
