### ISSUE TITLE
tunnel server offline: Request failed with status code 404, retry 1s

### ISSUE THREAD

**Issue by wanglong167** [localtunnel/server#81]
tunnel server offline: Request failed with status code 404, retry 1s

**Comment by agungyuliaji** [comment]
is it any reference why you close the issue? @defunctzombie

**Comment by agungyuliaji** [comment]
i have a same problem with nginx proxy

simple config:
```
server {

  server_name mydomain.com;

  listen 443 ssl;
  listen 80;

  location / {
    proxy_set_header Host $http_host;
    proxy_pass http://127.0.0.1:3000;
    proxy_buffering off;
  }
}
```

**Comment by defunctzombie** [comment]
There is not enough information described here to assist with debugging this issue.

**Comment by pengliheng** [comment]
![2018-08-12 20-41-29](https://user-images.githubusercontent.com/14355994/44002100-2f3ff69c-9e70-11e8-8a56-47aba843c1d2.png)
there is an problem with me ..
i never found this problem before i use window10  to do this....

but now  ,i use ubuntu18.04 ti run this
,,,,there is no problem   while i   type blow
```js
it -p 8002  
```
------------------------------

there is problem while i do this in  my person vpn....


i do as this blow code 
```js
# pick a place where the files will live
git clone git://github.com/defunctzombie/localtunnel-server.git
cd localtunnel-server
npm install

# server set to run on port 1234
bin/server --port 1234
```

**Comment by httpex** [comment]
Got localtunnel-server running.  But I get the following error:
"tunnel server offline: getaddrinfo ENOTFOUND 9999 9999:80, retry 1s"

I don't have a domain name yet and testing with just my host IP.  Will that not work?

Thanks,
Angel
