### ISSUE TITLE
subdomains not working 100%

### ISSUE THREAD

**Issue by kristianstage** [localtunnel/server#84]
Hi guys. hope someone is still working on localtunnel.me 

I have setup localtunnel server on a debian server on digitalocean.
and I am using raspberry pi as the LT client

first i have had alot of problems with server not closing connections after client disconnects, this i fixed by cronjob to kill process and restart if it crashed. also rebooting server a couple of times per day. its not optimal, but it gets it going for now (even a updated fork with this fixed would be highly apreciated)

but the issue i am facing now is when my client connects with --sub aaaaa ( which works fine )
at the same time if I try to reach bbbbb.domain.com:port it still shows the tunnel for aaaaa 

my idea was to have several raspberry pis running on their own subdomain on the server, but that is not going to work if all subdomains will point to the first one who connected.

Hope someone can help me out

Best regards

Kristian

**Comment by defunctzombie** [comment]
Sorry but there is not enough information in this post to provide help. This repository powers localtunnel.me so I am _fairly_ sure it works as expected (have not seen reports otherwise) however there could be bugs I am not aware of. Unfortunately I don't have the time to provide step-by-step support to setting up your localtunnel server (other than the README guide and source) but if you dig into this and do find a more specific problem I will be able to provide details.

**Comment by kristianstage** [comment]
it was fixed with Whitecolors fork
Thanks anyway

**Comment by gaamaaresosa** [comment]
> 
> 
> Hi guys. hope someone is still working on localtunnel.me
> 
> I have setup localtunnel server on a debian server on digitalocean.
> and I am using raspberry pi as the LT client
> 
> first i have had alot of problems with server not closing connections after client disconnects, this i fixed by cronjob to kill process and restart if it crashed. also rebooting server a couple of times per day. its not optimal, but it gets it going for now (even a updated fork with this fixed would be highly apreciated)
> 
> but the issue i am facing now is when my client connects with --sub aaaaa ( which works fine )
> at the same time if I try to reach bbbbb.domain.com:port it still shows the tunnel for aaaaa
> 
> my idea was to have several raspberry pis running on their own subdomain on the server, but that is not going to work if all subdomains will point to the first one who connected.
> 
> Hope someone can help me out
> 
> Best regards
> 
> Kristian

I am trying to run localtunel server in digialocean with ubuntu.
Couldn't success as I am very new to these technology.
Can you please help me ?

please read this link:
https://github.com/localtunnel/server/issues/141

**Comment by micahbule** [comment]
https://github.com/localtunnel/server/issues/141#issuecomment-771647320
