### ISSUE TITLE
Request Timed Out

### ISSUE THREAD

**Issue by zulfajuniadi** [localtunnel/server#86]
I've been trying to get localtunnel/server to run on an EC2 AWS instance. The client seem to connect (and get the subdomain) okay but requests to the subdomain are getting timed out. I'm running both the server and nginx via docker as per the repo's readme.md.

```
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS               NAMES
d84a573a26e1        localtunnel                              "node -r esm ./bin..."   9 minutes ago       Up 9 minutes                            localtunnel
f9f63a5deffe        defunctzombie/localtunnel-nginx:latest   "nginx -g 'daemon ..."   53 minutes ago      Up 8 minutes                            localtunnel-nginx
```

It's running on a micro EC2 instance (1CPU, 1GB Ram) with Ubuntu Server version 16.04

All incoming TCP ports > 1000 are opened, internal firewall is disabled.

Running curl on the domain?new returns a JSON string, so I guess nginx and nodejs are talking to each other successfully:

```
$ curl https://xxxxxx?new
{"port":32783,"max_conn_count":10,"id":"yellow-eel-34","url":"https://yellow-eel-34.xxxxxx"}
```

I've installed the wildcard cert successfully:

```
$ openssl s_client -showcerts -connect xxxxxxx:443
CONNECTED(00000005)
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/CN=*.xxxxxxx
```
Running docker logs on localtunnel doesn't show any errors. But localtunnel-nginx does:

```
2018/04/06 07:42:20 [error] 5#5: *6 upstream timed out (110: Operation timed out) while reading response header from upstream, client: x.x.x.x, server: , request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:3000/", host: "tricky-dog-77.xxxxxx"
```

How do I go around troubleshooting this?

**Comment by defunctzombie** [comment]
Try the latest version of the server - I have refactored a lot of the logic and it might point to a specific error better.
