### ISSUE TITLE
replasing named client

### ISSUE THREAD

**Issue by Spown** [localtunnel/server#87]
When trying to request a new tunnel with id/subdomain that was already requested a random one is being returned:
```
2018-04-10T01:05:42.163Z localtunnel:server making new client with id mycustomid
2018-04-10T01:05:42.164Z localtunnel:server:eprytkxfix tcp server listening on port: 45728
2018-04-10T01:05:42.246Z localtunnel:server:eprytkxfix new connection from: ::ffff:5.9.30.98:45728
```
I'm requesting the tunnel not via API (haven't tried ``tunnel.close()`` method so I don't know whether it would help) but via command line. Basically every time I restart my local tunnelable app I can't reach it anymore via the tunnel. So naturally I try to generate a new tunnel with the same id. 

``lt -h mylocaltunnelserver.tld -s mycustomid``

But instead of expected ``mycustomid.mylocaltunnelserver.tld`` i get something like ``eprytkxfix.mylocaltunnelserver.tld``. I don't know, maybe mycustomid has a ttl and I can regenerate it after some time but that would not be a solution anyway. Right now I have to restart the server every time.

I don't know if this is a by design. If it is please introduse an option to force replacement/overwriting which would terminate the old one before recreating it under the same id. Maybe it would be wise to allow this only from the remote ip that has created the first tunnel in the first place or do it with the help of secret words or something.

Thank you.

**Comment by siburny** [comment]
It will let you reuse the id once the existing client connection is closed.

**Comment by defunctzombie** [comment]
I have pushed a large refactor to the server code (and deployed the refactor to the localtunnel.me production version).

The behavior around releasing old client ids should be much improved (I did a lot of local testing around various restart conditions). The timeout for releasing an ID once your localtunnel client dies is now 1 second.
