### ISSUE TITLE
the localtunnel server offline?

### ISSUE THREAD

**Issue by Felix-Chk** [localtunnel/server#93]
I build a server like this 
`docker run -d     --restart always     --name localtunnel     --net host     defunctzombie/localtunnel-server:latest --port 3000`
netstat is already use in 3000

when i try to connnet the server ........
```
lt --host "http://support.xxx.com:3000" --port 22
tunnel server offline: Request failed with status code 404, retry 1s
tunnel server offline: Request failed with status code 404, retry 1s
tunnel server offline: Request failed with status code 404, retry 1s
tunnel server offline: Request failed with status code 404, retry 1s
```
What's wrong!!!!!!    It doesn't work!   
How to fix it ?

**Comment by defunctzombie** [comment]
You need to run with `--net host` localtunnel server requires the ability to create arbitrary ephemeral tcp sockets to accepts tunnel connections. This is how the protocol works with the localtunnel client.

**Comment by Felix-Chk** [comment]
I always run `--net host`   but  it doesn't work

**Comment by gregfr** [comment]
I have the same issue....
Using the direct server URL I have:
`tunnel server offline: Request failed with status code 404, retry 1s`
Using the nginx proxy:
`tunnel server offline: Request failed with status code 502, retry 1s`
Maybe I missed something in the configuration?
Thanks

**Comment by gregfr** [comment]
I found the problem: I'm using a subdomain for the entrypoint so I have to add `-- domain ...` to the `docker run` command.

**Comment by unitof** [comment]
To clarify what @gregfr figured out: that's the full subdomain you've pointed to your docker's IP address.

The full run command is then
```
docker run -d --restart always --name localtunnel --net host defunctzombie/localtunnel-server:latest --port 3000 --domain [sub.domain.tld]
```
…replacing `[sub.domain.tld]` with your custom subdomain.
