### ISSUE TITLE
Hostign localtunnel on a kubernetes cluster

### ISSUE THREAD

**Issue by cschroeter** [localtunnel/server#96]
Has anyone experience hosting localtunnel on a kubernetes cluster? I've it running but unfortunately I just can see a 404, after I've created a tunnel

**Comment by consti** [comment]
@cschroeter I'm running into the same issue - did you find a solution?

**Comment by cschroeter** [comment]
Yeah - it is apparently possible. But this violates some best practices in Kubernetes. We've ended up using Amazon ECS service.
